### ISSUE TITLE
Unable to smelt oreberries into Thermal Expansion Redstone Furnace

### ISSUE THREAD

**Issue by michelegargiulo** [ganymedes01/Another-One-Bites-The-Dust-Berry-Bushes#15]
After collecting some oreberries i tried to smelt them up into a fully powered basic redstone furnace from Thermal Expansion. The recipe is there, it is shown up in NEI, I just can't insert into the smelting slot, neither by shift-clicking or mouse clicking. I even tried adding a recipe for one of the oreberry via minetweaker, it seems that the furnace just refuses to do its job. All the other TE Redstone Furnace recipes work fine. The furnace is powered. I had to smelt oreberries into vanilla furnace. I don't think it is intended. There is a config option for that?

**Comment by buttilda** [comment]
I didn't code anything that interacts with TE, the ore berries are smeltable in the vanilla furnace, TE is the one doing something wrong when pulling the recipe. No idea what it could be, but you should report it to them

**Comment by michelegargiulo** [comment]
Ok, thank you for your time, I'll report to them, then. Thanks again and sorry for the mistake :p

**Comment by KingLemming** [comment]
This is sort of a complicated thing and I'm not sure if it's on you or Forge, although you could fix it quite easily.

Basically, OreDict queries are reporting back incorrectly, since you're registering the Furnace Recipe as a Wildcard, but the OreDict as well, I guess not one.

I can work around this on TE's end, but basically the reason we pull the recipe "wrong" is because you're sort of registering it "wrong," in so far as how the OreDictionary handles things.

**Comment by buttilda** [comment]
Strange that it should get confused over the wildcard.
But as you said, it's an easy fix on my side so I'll do it.
Thanks for pointing it out to me :)

**Comment by michelegargiulo** [comment]
Hey, thank You for fixing The issue so quickly! Already updated AOBD:BB, and thanks again for making my (virtual) Life easier!

**Comment by buttilda** [comment]
I'm glad the fix worked :3 Let me know if you have any other problems :)
